bump_version: null
lint: null
nf_core_version: 3.0.1
org_path: null
repository_type: pipeline
template:
  author: Christopher Mohr, Alexander Peltzer, Sven Fillinger
  description: Precision HLA typing from next-generation sequencing data.
  force: false
  is_nfcore: true
  name: hlatyping
  org: nf-core
  outdir: .
  skip_features: null
  version: 2.1.0dev
update: null
