lint:
  files_unchanged:
    - docs/images/nf-core-hlatyping_logo_dark.png
    - assets/nf-core-hlatyping_logo_light.png
nf_core_version: 4.0.0
repository_type: pipeline
template:
  author: Christopher Mohr, Alexander Peltzer, Sven Fillinger
  description: Precision HLA typing from next-generation sequencing data.
  force: false
  is_nfcore: true
  name: hlatyping
  org: nf-core
  outdir: .
  version: 2.2.0
